### ISSUE TITLE
How to compile??

### ISSUE THREAD

**Issue by QkiZMR** [simon3z/usbtv#5]
How to compile this module ??

**Comment by copywrong** [comment]
install git

git clone https://github.com/simon3z/usbtv
cd usbtv
edit Makefile and save it like this:

usbtv-y := usbtv-core.o \
    usbtv-video.o \
    usbtv-audio.o

obj-$(CONFIG_VIDEO_USBTV) += usbtv.o

all:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

After editing the file run:
make
insmod usbtv.ko

**Comment by QkiZMR** [comment]
Compiling passed without errors but can't insert module. Error:
insmod: ERROR: could not insert module usbtv.ko: Unknown symbol in module

**Comment by copywrong** [comment]
@QkiZMR I have the same issue.

**Comment by QkiZMR** [comment]
Use different kernel.

**Comment by copywrong** [comment]
@QkiZMR 
I use 3.14.6

**Comment by QkiZMR** [comment]
I'm using 3.13.0-24 (Ubuntu). But I must install usbtv.ko manually.

**Comment by hansdej** [comment]
Hi, I succesfully compiled it into the kernel 3.14.4-1 and am runing it now on a Debian Testing Platform.

When I plug the EasyCap USB stick in, a new ALSA card titled "usbtv" is generate, however (using VLC on a KDE desktop) I seem to miss the way how I can add the captured sound from the USB stick to the (succesfully streamed) composite stream.
As a user I want to: 
display the data on my (laptop) screen
hear the audio synchronised from the amplifier that is connected to the Computer's (Laptop) headphone jack.

The way I managed to get the composite signal visible with VLC:
(VLC=>Media=>OpenCaptureDevice:
Capture Mode = TV - Analog
Device name = /dev/video
Audio device name = (Choose: "hw:0,0" || "hwL1,0" but both give no sound eventually)
Options
Video Standard: PAL (works for NL)  
However I get no sound at all.

when I try to see if I can fumble with it through alsamixer (F6[choose usbtv]), so the USBTV device is generated when I plug it in, but I get the message "this sound device has no controls and I fail to see how I can use it.

Any ideas?

**Comment by QkiZMR** [comment]
Try capture sound with SoX:
sox -t pulseaudio default -t pulseaudio default

**Comment by hansdej** [comment]
Thanks, that indeed cats the sound direct and audiable to the speaker without a noticable delay (and without beeing aware of vlc's handling the video stream)

Time to lookup the SoX man-pages to see what this means and get some fine tuning (ways to merge/sync it with the image stream to enable pauses and so on)

**Comment by ipserc** [comment]
The driver can be installed as a Dynamic Kernel Module with DKMS. The steps to be taken are the following:

A. Terminate the Makefile as copywrong comments above:
usbtv-y := usbtv-core.o \
    usbtv-video.o \
    usbtv-audio.o

obj-$(CONFIG_VIDEO_USBTV) += usbtv.o

all:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

B. Create the dkms.conf and put inside this lines:
PACKAGE_NAME="usbtv"
PACKAGE_VERSION="2.0"
CLEAN="make clean"
MAKE="make KVERSION=$kernelver KERNELDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="usbtv"
DEST_MODULE_LOCATION[0]="/updates"

C. Follow the README written by mwelchuk at https://github.com/mwelchuk/usbtv/blob/master/README but use 2.0 instead of 1.0 

D. If everything was fine a lsmod | grep usbtv will shown us the module loaded. 

E. If the sound doesn't work QkiZMR shown us the power of sox a couple of comments above
A script called ps2sound in our local bin with the following code will be enough
#!/bin/bash
sox -t pulseaudio default -t pulseaudio default

**Comment by QkiZMR** [comment]
Nice tutorial :)

**Comment by ipserc** [comment]
Thanks, it is only a compilation of your work.

AND IT WORKS!!!!!!!!! (Not as my PS2, dvd device can't read dvds)

**Comment by aginzu** [comment]
My Makefile contains:
usbtv-y := usbtv-core.o \
    usbtv-video.o \
    usbtv-audio.o

obj-$(CONFIG_VIDEO_USBTV) += usbtv.o

all:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
    make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

When I try to compile I get:

make -C /lib/modules/3.2.0-61-generic-pae/build M=/usr/src/usbtv-1.1 modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-61-generic-pae'
  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-61-generic-pae'

Any idea why it won't compile anything?

**Comment by ipserc** [comment]
Please follow the indications given at https://github.com/mwelchuk/usbtv/blob/master/README and use 2.0 instead of 1.0 

Let me know if something goes wrong. I can't ensure that it works, your kernel seems to be slightly old and you need dkms installed. Other possible cause of the error is that you'll have installed a wrong linux headers package. 

If your kernel is the 3.2.0, a good starting point should be upgrading (in this case installing, I'm afraid) the kernel to a more recent release, the lastest would be the better option.

If your kernel is up-to-date, I don't understand why it is triying to compile against this set of headers. And why "uname -r" is  returning this kernel release.

By other hand I understand that you're root when you try to compile, I'm not sure but if you are "ubuntian", you'll need to use sudo as you know.

**Comment by aginzu** [comment]
I am running Ubuntu 12.04 LTS and have updated my kernel to 3.11 and now it
compiles and everything is working fine.  For some reason it would not
compile with the original 3.2 kernel in 12.04.

Thanks you very much for your help.

**Comment by ipserc** [comment]
You're welcome, but you are the one who has done all the work. This will
remain in a mystery, I guess...

**Comment by copywrong** [comment]
I can't build the module anymore using the kernel 3.16.1.

@ipserc Can you help me building the module with DKMS on Arch Linux? What sources do I extract into /usr/src/usbtv-2.0/ ? The dkms.conf is inside that folder and usbtv from git is in home folder.

**Comment by ipserc** [comment]
On 31/08/14 05:44, copywrong wrote:

> I can't build the module anymore using the kernel 3.16.1.
> 
> @ipserc https://github.com/ipserc Can you help me building the
> module with DKMS on Arch Linux? What sources do I extract into
> /usr/src/usbtv-2.0/ ? The dkms.conf is inside that folder and usbtv
> from git is in home folder.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/simon3z/usbtv/issues/5#issuecomment-53977360.
> 
> i'm going to be quite busy this week.

Let me review your case during the weekend.

Regards

**Comment by copywrong** [comment]
usbv got audio support.

http://lkml.iu.edu/hypermail/linux/kernel/1410.1/01112.html

**Comment by kbal264** [comment]
Sound in VLC is only working for me if I set the general delay greater than 145ms, which makes any kind of game unplayable. With sox it's working though.

![vlc_scart_setting](https://cloud.githubusercontent.com/assets/9553132/4900931/40886b68-642d-11e4-88fd-2d35c06294b8.jpg)

**Comment by Initiale** [comment]
anyone can send me compiled version can run on android 4.4.2 kitkat?????
